/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hiscene_dy_echoviewer_algProcessEx */

#ifndef _Included_com_hiscene_dy_echoviewer_algProcessEx
#define _Included_com_hiscene_dy_echoviewer_algProcessEx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hiscene_dy_echoviewer_algProcessEx
 * Method:    initJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hiscene_dy_echoviewer_algProcessEx_initJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_hiscene_dy_echoviewer_algProcessEx
 * Method:    runJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hiscene_dy_echoviewer_algProcessEx_runJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_hiscene_dy_echoviewer_algProcessEx
 * Method:    deinitJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hiscene_dy_echoviewer_algProcessEx_deinitJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
